agent {
        label 'main'
}

node {
    env.NODEJS_HOME = "${tool 'Node JS'}"
    env.PATH="${env.NODEJS_HOME}/bin:${env.PATH}"
    sh 'npm --version'
}

node {
    stage('Checkout') {
        checkout scm
    }

    stage('NPM Install') {
       dir('frontend') {
          sh 'npm install'
       }
    }

    stage('Lint') {
       dir('frontend') {
        //sh 'ng lint'
       }
    }

    stage('Build') {
        //milestone()

        dir('frontend') {
          sh 'ng build'
        }
    }

    stage('Archive') {
        //sh 'tar -cvzf dist.tar.gz --strip-components=1 dist'
        //archive 'dist.tar.gz'
    }

    stage('Crate Build Artifakt') {

    }
}
