pipeline {
    agent { label 'main' }

    parameters {
        string(
        name: 'CLEAN_UP',
        defaultValue: 'false',
        description: 'Do cleanup before build')
    }
    options {
        copyArtifactPermission('docker/Docker-Webseite')
    }
    stages {
      stage('Checkout') {
      steps {
      }
      }

      stage('NPM Install') {
      steps {
          dir('frontend') {
              sh 'npm install'
          }
      }
      }

      stage('Lint') {
      steps {
        dir('frontend') {
        //sh 'ng lint'
        }
      }
      }

      stage('Build') {
      //milestone()
      steps {
          dir('frontend') {
            nodejs(nodeJSInstallationName: 'Node JS') {
              sh 'ng build'
            }
          }
      }
      }

      stage('Archive') {
      steps {
      //sh 'tar -cvzf dist.tar.gz --strip-components=1 dist'
      //archive 'dist.tar.gz'
      }
      }

      stage('Crate Build Artifakt') {
      steps {
      }
      }

      stage('Create Artifact') {
          steps {
        sh 'mkdir -p target/zipfile_content'
        echo 'copying resources for zip file into target/zipfile_content'
        sh 'cp -r frontent/dist/angular-project target/zipfile_content'
        //sh "cp -r templates target/zipfile_content"
        //sh "cp target/release/rustwebserver target/zipfile_content"
        echo 'creating zip file'
        zip zipFile: 'target/server-manager-frontent.zip', archive: true, dir: 'target/zipfile_content', overwrite: true
          }
      }
    }

    post {
        always {
      archiveArtifacts artifacts: 'target/server-manager-frontent.zip', fingerprint: true

      emailext body: 'Build executed',
            recipientProviders: [developers(), requestor()],
            subject: 'jenkins build ${JOB_DESCRIPTION}: ${BUILD_STATUS}',
            to: 'christopher@christopherfuchs.de'
        }
    }
}
