version: "3"
services:
  timeseriesdb:
    image: questdb/questdb:latest
    # network also has to be host here - cannot combine bridge and host network. And the server has to stay in network mode host due to Wake On Lan - see comment for server container
    network_mode: host
    # should only be accessible for the host itself, so we bind it to localhost
    environment:
      - QDB_HTTP_BIND_TO=127.0.0.1

  server:
    image: afoxdocker/server-manager:latest
    container_name: server-manager
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    # if you want to use wake on lan actions, the network_mode has to be host
    # consequence -> if "network_mode: host" the port mapping doesn't work. You need to change the port of the internal server in the .env file in the config folder
    network_mode: host
    volumes:
      - ./config:/external_files
      - ./log:/var/log
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:r